name: website
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  constants:
    path: ../../packages/constants
  models:
    path: ../../packages/models
  util:
    path: ../../packages/util
  firebase:
    path: ../../packages/firebase
  repositories:
    path:  ../../packages/repositories
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  riverpod_annotation: ^3.0.0-dev.17
  riverpod_generator: ^3.0.0-dev.17
  flutter_riverpod: ^3.0.0-dev.17
  auto_size_text: ^3.0.0
  go_router: 16.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  responsive_framework: ^1.5.1
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  glassmorphism: ^3.0.0
  gap: ^3.0.1
  flutter_gradient_animation_text: ^1.0.2
  json_serializable: ^6.8.0
  url_launcher: ^6.3.2
  syncfusion_flutter_calendar: ^30.2.5
  intl: ^0.20.2

  freezed_annotation: ^3.0.0
  fpdart: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0

dependency_overrides:
  rxdart: ^0.28.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  custom_lint: any
  analyzer: ^7.6.0
  analyzer_plugin: 0.13.4
  build_runner: ^2.4.11
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/

  # Custom fonts configuration
  fonts:
    - family: FunFont  # This is the name you will use in your code
      fonts:
        - asset: assets/fonts/fun_font.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
